modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues"

[[mods]]
modId = "easy_mob_farm"
version = "${file.jarVersion}"
displayName = "Easy Mob Farm"
displayURL = "https://curseforge.com/minecraft/mc-mods/easy-mob-farm"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''The Easy Mob Farm offers a server-friendly solution for capturing various animals and mobs to
harvest their valuable loot.'''

[[dependencies.easy_mob_farm]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_mob_farm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
