plugins {
  id 'net.fabricmc.fabric-loom-remap' version "${fabric_loom}"
  id 'net.darkhax.curseforgegradle' version '1.1.28'
  id 'nu.studer.credentials' version '3.0'
  id "com.modrinth.minotaur" version "2.+"
}

base {
  archivesName = "${mod_id}-fabric-${minecraft_version}"
}

loom {
  // Access Widener
  accessWidenerPath = file("src/main/resources/${mod_namespace}.accesswidener")

  // Run configurations
  runs {
    client {
      client()
      setConfigName("Fabric Client")
      property("fabric.logging.markers", "REGISTRIES")
      property("fabric.log.level", "debug")
      property("mixin.debug.verbose", "false")
      property("mixin.debug.export", "false")
      ideConfigGenerated(true)
      runDir("run")
    }
    server {
      server()
      setConfigName("Fabric Server")
      property("fabric.logging.markers", "REGISTRIES")
      property("fabric.log.level", "debug")
      property("mixin.debug.verbose", "false")
      property("mixin.debug.export", "false")
      ideConfigGenerated(true)
      runDir("run")
    }
    gameTest {
      server()
      name "Game Test"
      vmArg "-Dfabric-api.gametest"
    }
  }
}

dependencies {
  minecraft "com.mojang:minecraft:${minecraft_version}"
  mappings loom.officialMojangMappings()
  modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
  modApi "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

  // Include Common code
  implementation project(":Common")

  // Additional helpful Mods for development (runtime dependency)
  if (project.hasProperty('fabric_jei_mod') && project.fabric_jei_mod) {
    modCompileOnlyApi("curse.maven:jei-238222:${project.fabric_jei_mod}")
    modRuntimeOnly("curse.maven:jei-238222:${project.fabric_jei_mod}")
  }
  if (project.hasProperty('fabric_spark_mod') && project.fabric_spark_mod) {
    modRuntimeOnly("curse.maven:spark-361579:${project.fabric_spark_mod}")
  }
  if (project.hasProperty('fabric_xaeros_minimap_mod') && project.fabric_xaeros_minimap_mod) {
    modRuntimeOnly("curse.maven:xaeros_minimap-263420:${project.fabric_xaeros_minimap_mod}")
  }

  // Bug Testing
  // modRuntimeOnly("curse.maven:polymer-551890:6012918")
  // modRuntimeOnly("curse.maven:trailier-tales-1124703:5960030")

  // Refined Storage: Integration Tests
  // modRuntimeOnly "curse.maven:cloth-config-348521:5729125"
  // modRuntimeOnly "curse.maven:refined-storage-243076:6391988"
  // modRuntimeOnly('teamreborn:energy:4.1.0') {
  //  exclude(group: "net.fabricmc.fabric-api")
  //}

  // Create: Integration Tests
  //  modRuntimeOnly "io.github.tropheusj:milk-lib:1.2.60"
  //  modRuntimeOnly "com.jamieswhiteshirt:reach-entity-attributes:2.4.0"
  //  modRuntimeOnly "com.tterrag.registrate:Registrate:MC1.20-1.3.11"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:accessors:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:base:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:entity:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:extensions:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:networking:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:obj_loader:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:tags:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:transfer:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:models:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:model_generators:2.3.4+1.20.1"
  //  modRuntimeOnly "io.github.fabricators_of_create.Porting-Lib:client_events:2.3.4+1.20.1"
  //  modRuntimeOnly "curse.maven:forge-config-api-port-fabric-547434:5902421"
  //  modRuntimeOnly "curse.maven:create-fabric-624165:5245234"

  // Swampier Swamps Tests
  // modRuntimeOnly "curse.maven:cloth-config-348521:5729104"
  // modRuntimeOnly "curse.maven:swampier-swamps-fabric-687298:4580758"
}

processResources {
  from project(":Common").sourceSets.main.resources
  inputs.property "version", project.version

  filesMatching("fabric.mod.json") {
    expand "version": project.version
  }
}

tasks.withType(JavaCompile).configureEach {
  source(project(":Common").sourceSets.main.allSource)
}

tasks.withType(Test).configureEach {
  failOnNoDiscoveredTests = false
}

tasks.named('build') {
  dependsOn 'remapJar'
}

test {
  useJUnitPlatform()
  exclude '**/*'
}

// CurseForge Publishing
if (project.hasProperty('curseforge_project_id') && project.curseforge_project_id) {
  tasks.register('curseforge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    group = 'publishing'
    description = 'Uploads to CurseForge'
    apiToken = "${credentials.forKey('curseforge_api_token')}"

    def mainFile = upload(project.curseforge_project_id, remapJar)
    mainFile.changelogType = 'markdown'
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.releaseType = "${project.curseforge_release_type}"
    mainFile.addModLoader('Fabric')
    mainFile.addModLoader('Quilt')
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.addRequirement('fabric-api')
  }
}

// Modrinth Publishing
if (project.hasProperty('modrinth_project_id') && project.modrinth_project_id) {
  modrinth {
    token = "${credentials.forKey('modrinth_api_token')}"
    projectId = "${project.modrinth_project_id}"
    versionNumber = "${version}"
    versionType = "${project.modrinth_release_type}"
    versionName = "${project.mod_name} ${project.version}"
    changelog = rootProject.file("CHANGELOG.md").text
    uploadFile = remapJar
    gameVersions = ["${minecraft_version}"]
    loaders = ["fabric", "quilt"]
    dependencies {
      required.project "fabric-api"
      optional.project "tooltipfix"
    }
  }
}
