# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
version=8.5.2
group=de.markusbordihn.easymobfarm
vendor_name=markusbordihn
# Mod
mod_id=easy_mob_farm
mod_name=Easy Mob Farm
mod_author=Markus Bordihn
mod_namespace=easymobfarm
# Common
minecraft_version=1.18.2
# Forge Mod Loader
forge_version=40.2.21
# Forge Helper Mods
forge_jei_mod=4593548
forge_spark_mod=4505375
forge_xaeros_minimap_mod=3712760
# Fabric Mod Loader
fabric_version=0.77.0+1.18.2
fabric_loader_version=0.15.11
fabric_loom=1.7-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=5534397
fabric_spark_mod=4533222
fabric_xaeros_minimap_mod=5394766
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=563464
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=crxsDbEo
modrinth_api_token=Never put your token here!
