# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
version=10.2.0
group=de.markusbordihn.easymobfarm
vendor_name=markusbordihn
# Mod
mod_id=easy_mob_farm
mod_name=Easy Mob Farm
mod_author=Markus Bordihn
mod_namespace=easymobfarm
# Common
minecraft_version=1.21.10
neo_form_version=1.21.10-20251010.172816
# Forge Mod Loader
forge_version=60.0.18
# Forge Helper Mods
forge_jei_mod=
forge_xaeros_minimap_mod=
# Fabric Mod Loader
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.17.3
fabric_loom=1.13-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=7182173
fabric_xaeros_minimap_mod=
# NeoForge Mod Loader
neoforge_version=21.10.51-beta
# NeoForge Helper Mods
neoforge_jei_mod=7182174
neoforge_xaeros_minimap_mod=
# Publish to CurseForge
curseforge_release_type=beta
curseforge_project_id=563464
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=beta
modrinth_project_id=crxsDbEo
modrinth_api_token=Never put your token here!
