# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
version=10.0.1
group=de.markusbordihn.easymobfarm
vendor_name=markusbordihn
# Mod
mod_id=easy_mob_farm
mod_name=Easy Mob Farm
mod_author=Markus Bordihn
mod_namespace=easymobfarm
# Common
minecraft_version=1.21.8
neo_form_version=1.21.8-20250717.133445
# Forge Mod Loader
forge_version=58.0.1
# Forge Helper Mods
forge_jei_mod=
forge_xaeros_minimap_mod=
# Fabric Mod Loader
fabric_version=0.130.0+1.21.8
fabric_loader_version=0.16.14
fabric_loom=1.11-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=
fabric_xaeros_minimap_mod=
# NeoForge Mod Loader
neoforge_version=21.8.17
# NeoForge Helper Mods
neoforge_jei_mod=
neoforge_xaeros_minimap_mod=
# Publish to CurseForge
curseforge_release_type=beta
curseforge_project_id=563464
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=beta
modrinth_project_id=crxsDbEo
modrinth_api_token=Never put your token here!
