plugins {
  id 'net.neoforged.moddev' version '1.0.23'
}

archivesBaseName = "${mod_name}-common-${minecraft_version}"

neoForge {
  neoFormVersion = neo_form_version
  version(minecraft_version)
  parchment {
    minecraftVersion = minecraft_version
    mappingsVersion = parchment_version
  }
}

dependencies {
  compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.7'
}

processResources {
  def buildProps = project.properties.clone()

  filesMatching(['pack.mcmeta']) {
    expand buildProps
  }
}
